### ISSUE TITLE
Use 404 Page Responsive Page Template 

### ISSUE THREAD

**Issue by ni3mumbaikar** [ni3mumbaikar/url-shortner#3]

**Comment by ni3mumbaikar** [comment]
**404 added** with in this commit [d1ce706572b3d5cba9437307b3702ce842735ebe](https://github.com/ni3mumbaikar/url-shortner/commit/d1ce706572b3d5cba9437307b3702ce842735ebe) verify it and mark as closed @AyusshM

**Comment by AyusshM** [comment]
Fixed the issue [here](https://github.com/ni3mumbaikar/url-shortner/commit/d1ce706572b3d5cba9437307b3702ce842735ebe).
